#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ミニコロ助 音声クリップ生成 (Open JTalk / 完全オフライン)

コロ助の声質は本体と同一 (personality.py 準拠):
    -fm 9   声の高さ(高め)     OJ_FM
    -a 0.40 声道長(子供っぽい)  OJ_A
    -r 1.12 話速               OJ_R

出力:
    assets/mini_voice/<category>_<nn>.wav        … MAX98357A(I2S)で鳴らすPCM WAV
    assets/mini_voice/manifest.json              … 一覧(file/category/emotion/text)
    firmware/mini_korosuke/include/voice_clips.h … ファーム用の生成ヘッダ(カテゴリ別配列)

使い方:
    # Linux(RDK等, open_jtalkがある環境)で実際に生成
    python3 tools/mini_voice_gen.py

    # Windows等で先にマニフェスト/ヘッダだけ作る(WAVは作らない)
    python  tools/mini_voice_gen.py --dry-run

    # パス上書き
    python3 tools/mini_voice_gen.py --open-jtalk open_jtalk \
        --dic /var/lib/mecab/dic/open-jtalk/naist-jdic \
        --voice /usr/share/hts-voice/nitech-jp-atr503-m001/nitech_jp_atr503_m001.htsvoice

emotion は目ファームの8種に丸める: neutral/happy/happy2/sad/angry/surprised/sleepy/thinking
"""
import argparse
import json
import os
import shutil
import subprocess
import sys

# ---- コロ助の声(personality.py の OJ_* をそのまま) ----
OJ_FM = "9"        # -fm 声の高さ
OJ_A  = "0.40"     # -a  声道長
OJ_R  = "1.12"     # -r  話速
OJ_SR = "16000"    # -s  出力サンプリング周波数(ESP32 I2S向けに軽量化。48000も可)

DEFAULT_DIC   = "/var/lib/mecab/dic/open-jtalk/naist-jdic"
DEFAULT_VOICE = "/usr/share/hts-voice/nitech-jp-atr503-m001/nitech_jp_atr503_m001.htsvoice"

# ---- 台本(短く1〜2文・「〜ナリ」口調) ----
# (category, emotion, text)。同一categoryは実行時にランダム選択する想定。
CLIPS = [
    # 起動・あいさつ
    ("greet", "happy",  "やあ！ワガハイはコロ助ナリ！"),
    ("greet", "happy",  "こんにちはナリ！元気ナリか？"),
    ("greet", "happy2", "会えて嬉しいナリ！"),
    # なで(画面タッチ)反応
    ("pet",   "happy",  "くすぐったいナリ〜！"),
    ("pet",   "happy2", "気持ちいいナリ！"),
    ("pet",   "happy",  "もっと撫でてほしいナリ！"),
    ("pet",   "happy2", "えへへ、嬉しいナリ！"),
    # 顔を見つけた(カメラ検出)
    ("found", "surprised", "あ、見つけたナリ！"),
    ("found", "happy",     "そこにいたナリか！"),
    ("found", "happy",     "ワガハイを見てるナリ？"),
    # ひとりごと(アイドル)
    ("idle",  "neutral",  "ご主人様はどこナリ？"),
    ("idle",  "thinking", "何か面白いこと無いナリか？"),
    ("idle",  "neutral",  "ひまだナリ…"),
    ("idle",  "happy",    "コロッケ食べたいナリ〜！"),
    # 驚き
    ("surprise", "surprised", "わわっ、びっくりしたナリ！"),
    ("surprise", "surprised", "なんとナリ！"),
    # 眠い
    ("sleepy", "sleepy", "ねむいナリ…ふぁ〜あ"),
    ("sleepy", "sleepy", "おやすみナリ…"),
]

REPO_ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR     = os.path.join(REPO_ROOT, "assets", "mini_voice")
HEADER_PATH = os.path.join(REPO_ROOT, "firmware", "mini_korosuke", "include", "voice_clips.h")
# ファーム側でSDをマウントするルート(microSDの /voice/ に配置する想定)
SD_PREFIX   = "/voice"


def synth(oj_bin, dic, voice, text, out_wav):
    """1クリップをOpen JTalkで合成。text は stdin へ渡す。"""
    args = [oj_bin, "-x", dic, "-m", voice,
            "-fm", OJ_FM, "-a", OJ_A, "-r", OJ_R, "-s", OJ_SR,
            "-ow", out_wav]
    p = subprocess.run(args, input=text.encode("utf-8"),
                       stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    if p.returncode != 0:
        raise RuntimeError(f"open_jtalk failed ({p.returncode}): {p.stderr.decode('utf-8','ignore')}")


def write_manifest(entries):
    with open(os.path.join(OUT_DIR, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)


def write_header(entries):
    """カテゴリ別の {file, emotion} 配列を持つ C++ ヘッダを生成。"""
    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    cats = {}
    for e in entries:
        cats.setdefault(e["category"], []).append(e)
    lines = [
        "// AUTO-GENERATED by tools/mini_voice_gen.py — 手で編集しない",
        "// ミニコロ助の音声クリップ一覧(カテゴリ別)。ファイルはSDの /voice/ に置く。",
        "#pragma once",
        "",
        "struct VoiceClip { const char* file; const char* emotion; };",
        "",
    ]
    for cat, items in cats.items():
        arr = f"VOICE_{cat.upper()}"
        lines.append(f"static const VoiceClip {arr}[] = {{")
        for e in items:
            lines.append(f'  {{ "{SD_PREFIX}/{e["file"]}", "{e["emotion"]}" }},')
        lines.append("};")
        lines.append(f"static const int {arr}_N = {len(items)};")
        lines.append("")
    with open(HEADER_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser(description="ミニコロ助 音声クリップ生成 (Open JTalk)")
    ap.add_argument("--open-jtalk", default=os.environ.get("OJ_BIN", "open_jtalk"))
    ap.add_argument("--dic",   default=os.environ.get("OJ_DIC", DEFAULT_DIC))
    ap.add_argument("--voice", default=os.environ.get("OJ_VOICE", DEFAULT_VOICE))
    ap.add_argument("--dry-run", action="store_true",
                    help="WAVを作らず manifest.json とヘッダだけ生成(Windowsで下ごしらえ用)")
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)

    oj = shutil.which(args.open_jtalk) if not args.dry_run else None
    if not args.dry_run and oj is None:
        print(f"[!] open_jtalk が見つからない: {args.open_jtalk}", file=sys.stderr)
        print("    Linux(RDK等)で実行するか、--dry-run でマニフェスト/ヘッダだけ先に作れます。",
              file=sys.stderr)
        print("    例) sudo apt-get install open-jtalk open-jtalk-mecab-naist-jdic hts-voice-nitech-jp-atr503-m001",
              file=sys.stderr)
        return 2

    # カテゴリ毎に連番を振る
    counters = {}
    entries = []
    for cat, emo, text in CLIPS:
        idx = counters.get(cat, 0)
        counters[cat] = idx + 1
        fname = f"{cat}_{idx:02d}.wav"
        out_wav = os.path.join(OUT_DIR, fname)
        if not args.dry_run:
            synth(oj, args.dic, args.voice, text, out_wav)
            print(f"[ok] {fname}  <- {text}")
        else:
            print(f"[dry] {fname}  <- {text}")
        entries.append({"file": fname, "category": cat, "emotion": emo, "text": text})

    write_manifest(entries)
    write_header(entries)
    print(f"\n出力: {OUT_DIR}")
    print(f"ヘッダ: {HEADER_PATH}")
    print(f"クリップ数: {len(entries)}  カテゴリ: {sorted(counters)}")
    if args.dry_run:
        print("※ --dry-run: WAVは未生成。open_jtalkのある環境で --dry-run なしで再実行してください。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
