// AUTO-GENERATED by tools/mini_voice_gen.py — 手で編集しない
// ミニコロ助の音声クリップ一覧(カテゴリ別)。ファイルはSDの /voice/ に置く。
#pragma once

struct VoiceClip { const char* file; const char* emotion; };

static const VoiceClip VOICE_GREET[] = {
  { "/voice/greet_00.wav", "happy" },
  { "/voice/greet_01.wav", "happy" },
  { "/voice/greet_02.wav", "happy2" },
};
static const int VOICE_GREET_N = 3;

static const VoiceClip VOICE_PET[] = {
  { "/voice/pet_00.wav", "happy" },
  { "/voice/pet_01.wav", "happy2" },
  { "/voice/pet_02.wav", "happy" },
  { "/voice/pet_03.wav", "happy2" },
};
static const int VOICE_PET_N = 4;

static const VoiceClip VOICE_FOUND[] = {
  { "/voice/found_00.wav", "surprised" },
  { "/voice/found_01.wav", "happy" },
  { "/voice/found_02.wav", "happy" },
};
static const int VOICE_FOUND_N = 3;

static const VoiceClip VOICE_IDLE[] = {
  { "/voice/idle_00.wav", "neutral" },
  { "/voice/idle_01.wav", "thinking" },
  { "/voice/idle_02.wav", "neutral" },
  { "/voice/idle_03.wav", "happy" },
};
static const int VOICE_IDLE_N = 4;

static const VoiceClip VOICE_SURPRISE[] = {
  { "/voice/surprise_00.wav", "surprised" },
  { "/voice/surprise_01.wav", "surprised" },
};
static const int VOICE_SURPRISE_N = 2;

static const VoiceClip VOICE_SLEEPY[] = {
  { "/voice/sleepy_00.wav", "sleepy" },
  { "/voice/sleepy_01.wav", "sleepy" },
};
static const int VOICE_SLEEPY_N = 2;
